name: Compile Games Windows
on: [repository_dispatch]

jobs:
  install-splashkit-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc

      - name: Install SplashKit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)
      
      # Add splashkit to path
      - name: Add splashkit to path
        run: echo setx MSYS2_PATH_TYPE inherit

        # Add splashkit to path
      - name: Add splashkit to path try 1
        run: . install/setup.bash

      # Display the splashkit directory
      - name: Test SplashKit
        run: echo ls ~/.splashkit

      # Check if SplashKit is installed
      - name: Install dependencies, compile splashkit
        run: skm help

      - name: "branch"
        run: echo "$GITHUB_REF"


