name: Compile Games Windows
on: [repository_dispatch]

jobs:
  install-splashkit-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh


