name: Compile Games Windows
on: 
  repository_dispatch:
  pull_request: 
      branches: [ master ] 

jobs:
  install-splashkit-windows:
    runs-on: windows-latest
    env:
      GAME_DIR:
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc
        
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SplashKit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)

      - name: Find added game
        run: |
          cd $GITHUB_WORKSPACE
          $GAME_DIR=$(git diff origin/master...origin/${GITHUB_HEAD_REF} --dirstat --diff-filter=AM arcade-games/ | sed 's/^[ 0-9.]\+% //g')
          echo "GAME_DIR=$GAME_DIR" >> $GITHUB_ENV
          echo Branch: $GITHUB_HEAD_REF, Game Location: $GAME_DIR

      - name: Compile Game
        run: |               
              cd /home/runneradmin/.splashkit                            
              ./skm clang++ $GITHUB_WORKSPACE/$GAME_DIR/program.cpp -o $GITHUB_WORKSPACE/$GAME_DIR/program.exe 

      - name: Get dir and files
        run: pwd && ls

      - name: Git Add, Commit, Push 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add $GAME_DIR
          git commit -m "Compiled Game"
          git push