name: Compile Games Windows
on: 
  repository_dispatch:
  pull_request: 
      branches: [ master ] 

jobs:
  install-splashkit-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc

      - name: Install SplashKit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)

      - name: Find added game
        run: |
          cd $GITHUB_WORKSPACE
          git diff origin/master...origin/${GITHUB_HEAD_REF} --dirstat --diff-filter=AM games/
          echo "GAME_DIR=$GAME_DIR" >> $GITHUB_ENV
          echo Branch: $GITHUB_HEAD_REF, Game Location: $GAME_DIR

      - name: Compile Game
        run: | 
              pwd && ls
              cd /home/runneradmin/.splashkit
              pwd && ls
              ./skm help
              echo "./skm" >> $GITHUB_PATH
              ./skm clang++ $GITHUB_WORKSPACE/$GAME_DIR/program.cpp -o $GITHUB_WORKSPACE/$GAME_DIR/program.exe 

      - name: Get dir and files
        run: pwd && ls

      - name: Git Add, Commit, Push 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add $GAME_DIR
          git commit -m "Compiled Game"
          git push