name: Compile Games Linux
on: 
  repository_dispatch:
  pull_request: 
      branches: [ master ] 


jobs:
  install-splashkit:
    runs-on: ubuntu-latest
    env:
      GAME_DIR: 
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SplashKit
        run: | 
          bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)
      # after install splashkit step check if it is installed
      - name: Add splashkit to path
        run: echo "$HOME/.splashkit" >> $GITHUB_PATH
      - name: Install dependencies, compile splashkit
        run: |
          skm linux install
      - name: Find added game
        run: |
          cd $GITHUB_WORKSPACE
          GAME_DIR=$(git diff origin/master...origin/${GITHUB_HEAD_REF} --dirstat --diff-filter=AM arcade-games/ | sed 's/^[ 0-9.]\+% //g')
          echo "GAME_DIR=$GAME_DIR" >> $GITHUB_ENV
          echo Branch: $GITHUB_HEAD_REF, Game Location: $GAME_DIR
      - name: Compile Game
        run: |
          cd $GITHUB_WORKSPACE/$GAME_DIR
          echo Compiling game...
          skm clang++ program.cpp -o attempt33
      - name: Git Add, Commit, Push
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add $GAME_DIR
          git commit -m "compiled game"
          git push origin HEAD:${GITHUB_HEAD_REF}
          echo done