name: Compile Games Windows
on: [repository_dispatch]

jobs:
  install-splashkit-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc

      - name: Install SplashKit
        run: bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)
      
      # Set path to inherit from parent environment
      - name: Add splashkit to path
        run: echo setx MSYS2_PATH_TYPE inherit

      # - shell: powershell
      #   run: msys2 -c 'uname -a'

      # - shell: powershell
      #   run: msys2 -c 'echo "export PATH=$PATH:/the/dir/you/want/to/add" >> ~/.bashrc | source ~/.bashrc'

      # - shell: powershell
      #   run: msys2 -c 'skm help'

      - name: ls
        run: ls

      - name: Move into splashkit directory
        run: cd /home/runneradmin/.splashkit

      - name: Test
        run: | 
              pwd
              cd /home/runneradmin
              echo "./.splashkit" >> $GITHUB_PATH
              pwd
              ls
              pwd
            

      - name: dirty hack to get around the fact that the msys2 setup script doesn't set the PATH variable
        run: echo "export PATH=$PATH:/home/runneradmin/.splashkit" >> ~/.bashrc | source ~/.bashrc

      # - name: ls
      #   working-directory: ~/home/runneradmin/.splashkit
      #   run: ls


      - name: Add splashkit to path
        run: echo "$HOME/.splashkit" >> $GITHUB_PATH

      # Check if SplashKit is installed
      - name: Install dependencies, compile splashkit
        run: skm help

      # - name: "branch"
      #   run: echo "$GITHUB_REF"

# Splashkit compile arguments
      # g++ $CPP_OPTIONS -Wl,--as-needed -L"${APP_PATH}/lib/win64" -static-libstdc++ -static-libgcc -lSplashKit -Wl,-Bstatic -lstdc++ -lpthread -I "${APP_PATH}/include" -I "${APP_PATH}/../" -L "${SKM_PATH}/lib/win64" -I "$APP_PATH/src" -I "$APP_PATH/win_include" $* "${APP_PATH}/lib/win64/libSplashKitCpp.a"
